USE SCOTT;
#################### EMPLOYEE MANAGER RELATIONSHIP #########################

#71
SELECT ENAME FROM EMP WHERE
EMPNO= (SELECT MGR FROM EMP WHERE ENAME='SMITH'); 

#72
SELECT ENAME FROM EMP WHERE
EMPNO= (SELECT MGR FROM EMP WHERE
EMPNO=(SELECT MGR FROM EMP WHERE ENAME='ADAMS'));

#73
SELECT DNAME FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO FROM EMP 
WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME= 'JONES'));

SELECT * FROM EMP;
#74
SELECT SAL FROM EMP 
WHERE EMPNO=(SELECT MGR FROM EMP 
WHERE ENAME='MILLER');

#75
SELECT LOC FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO FROM EMP
WHERE EMPNO=(SELECT MGR FROM EMP WHERE 
ENAME='SMITH'));

#76
SELECT ENAME FROM EMP
WHERE MGR=(SELECT EMPNO FROM EMP WHERE ENAME='BLAKE');

#77
SELECT COUNT(*)
FROM EMP
WHERE MGR= (SELECT EMPNO FROM EMP WHERE ENAME='KING');

#78
SELECT * FROM
EMP WHERE MGR=(SELECT EMPNO FROM EMP WHERE ENAME='JONES');

#79
SELECT ENAME 
FROM EMP WHERE
MGR=(SELECT MGR FROM EMP WHERE ENAME ='BLAKE');

#80
SELECT COUNT(*)
FROM EMP 
WHERE MGR= (SELECT MGR FROM EMP WHERE ENAME='FORD');

################################# INNER JOIN #############################

 select ename,loc from emp e inner join dept d ON e.deptno=d.deptno;

-- 2
select dname,sal from emp e inner join dept d on e.deptno=d.deptno where d.dname='ACCOUNTING';

-- 3
 select dname,(sal*12) annual_salary from emp e join dept d on e.deptno=d.deptno where e.sal>2340;

-- 4
 select ename,dname from emp join dept ON emp.deptno=dept.deptno where ename like '%a%';
 
 -- 5
 SELECT ENAME, DNAME
 FROM EMP JOIN DEPT ON EMP.DEPTNO= DEPT.DEPTNO
 WHERE EMP.JOB= 'SALESMAN';
 
 -- 6
 SELECT DNAME, JOB FROM EMP JOIN DEPT ON EMP.DEPTNO= DEPT.DEPTNO
 WHERE DEPT.DNAME LIKE 'S%';
 
 -- 7
 SELECT DNAME, MGR FROM EMP E JOIN DEPT D
 ON E.DEPTNO= D.DEPTNO
 WHERE E.MGR= 7839;
 
 -- 8 //ORACLE SYNTAX FOR JOIN
 SELECT DNAME , HIREDATE FROM 
 EMP, DEPT
 WHERE EMP.DEPTNO= DEPT.DEPTNO AND 
 HIREDATE>'1983-12-31' AND DEPT.DNAME IN ('ACCOUNTING', 'RESEARCH');
 
 
 -- 9
 SELECT ENAME, DNAME 
 FROM EMP E JOIN DEPT D
 ON E.DEPTNO= D.DEPTNO
 WHERE E.COMM IS NOT NULL AND  D.DEPTNO IN (10,30);
 
 -- 10
 SELECT DNAME, EMPNO
 FROM EMP E JOIN DEPT D
 ON E.DEPTNO= D.DEPTNO
 WHERE E.EMPNO IN (7839,7902) AND D.LOC='NEW YORK';